### ISSUE TITLE
Issue with sort / reverse sort option

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/mapcidr#103]
**Describe the bug**
When `-s` or `-sr` flag is used, it looks like `-a` option is used internally, and sorting/reverse sorting is performed on the aggregated data, whereas default sorting and reverse sorting need to performed on the expanded IPs.

**Mapcidr version**
master

```console
$ cat input.txt

1.1.1.1
8.8.8.8
255.255.255.255
2.2.2.2
2.4.4.4
2.4.3.2
9.9.9.9
```

Current:

```console
cat input.txt | mapcidr -s

1.1.1.1/32
2.2.2.2/32
2.4.3.2/32
2.4.4.4/32
8.8.8.8/32
9.9.9.9/32
255.255.255.255/32
```

Expected:

```console
cat input.txt | mapcidr -s

1.1.1.1
2.2.2.2
2.4.3.2
2.4.4.4
8.8.8.8
9.9.9.9
255.255.255.255
```

**Comment by ShubhamRasal** [comment]
#104
