### ISSUE TITLE
Maps CIDR Range of Not Specified Range in List

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/mapcidr#164]
**Describe the bug**

cat test.txt
```bash
10.35.148.0/22
10.35.20.0/24
```

the test.txt file contains only subnet of 10.35.148 & 10.35.20 

but when i ran this command 

```bash
mapcidr -cidr test.txt 
```

It displays results of range that are not specified example output 

```bash
10.35.150.252
10.35.150.253
10.35.150.254
10.35.150.255
10.35.151.0
10.35.151.1
10.35.151.2
```

From the above , it can be observed that 10.35.150 & 10.35.151 range is not in scope of the list that is supplied, but mapcidr displays those results as well 

**Mapcidr version**
v1.0.3

**Complete command you used to reproduce this**

**Screenshots**
Add screenshots of the error for a better context.

**Comment by Mzack9999** [comment]
@DhiyaneshGeek I think that the described behavior is correct, since the network is `/22` it spans over 4 class C networks:
```
10.35.148.0/24
10.35.149.0/24
10.35.150.0/24
10.35.151.0/24
```

You can cross-check at https://www.ipaddressguide.com/cidr 
![image](https://user-images.githubusercontent.com/13421144/225764490-10a76f0c-d37e-4210-b948-74ce9914330c.png)

**Comment by DhiyaneshGeek** [comment]
Hi @Mzack9999 Thanks for the clarification
