### ISSUE TITLE
static pre compiled assets gone after v1.1.19.

### ISSUE THREAD

**Issue by SkyperTHC** [projectdiscovery/mapcidr#264]
The pre-compiled assets are gone from all releases after v1.1.19. Please bring them back.

**Comment by ehsandeep** [comment]
Fixed with release https://github.com/projectdiscovery/mapcidr/releases/tag/v1.1.14

**Comment by MetzinAround** [comment]
This should be resolved with the most recent version! Thanks for the issue! 

https://github.com/projectdiscovery/mapcidr/releases/tag/v1.1.14
