### ISSUE TITLE
[FTL] invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by ayoubackup** [projectdiscovery/mapcidr#272]
echo AS15133 | mapcidr -silent

[FTL] invalid character '<' looking for beginning of value

also

cat asns.txt | mapcidr -silent

[FTL] invalid character '<' looking for beginning of value

**Comment by ehsandeep** [comment]
@ayoubackup see https://github.com/projectdiscovery/asnmap/issues/198
