### ISSUE TITLE
mapcidr uses too much RAM and crashes laptop

### ISSUE THREAD

**Issue by aerosayan** [projectdiscovery/mapcidr#30]
**Describe the bug**
`echo 17.0.0.0/8 | mapcidr -silent` uses up almost 1.5 GB RAM memory, and `echo 17.0.0.0/2 | mapcidr -silent` makes the computer unresponsive after consuming all of my 4 GB RAM. I'm submitting this as a bug report, **since such high memory usage should have been documented well as a clear WARNING in the README.md,** and even though I'm not very knowledgeable about mapcidr, I think such high memory requirement shouldn't be necessary for basic use as shown above. 

Obviously some huge amount of dynamic memory allocation is happening inside the code. 
Is that really required for expanding out the given input into IPs?
I would imagine it would be possible to simply print out the information directly without any memory allocation, or at least do it in batches so that memory requirement isn't so high.

**Mapcidr version**
v0.0.7

**Complete command you used to reproduce this**
`echo 17.0.0.0/8 | mapcidr -silent` and `echo 17.0.0.0/2 | mapcidr -silent`

**Comment by ehsandeep** [comment]
Hi @aerosayan, thanks for reporting this, High uses of memory was not intended as such we fixed this issue in linked PR.

**Comment by ehsandeep** [comment]
A new release is pushed for mapCIDR including fix for this issue.
