### ISSUE TITLE
[Issue] using mapcidr as a lib in readme points to a wrong function name

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/mapcidr#5]
Hi guys,
Found that your lib offers a mapcidr.IPAddresses function, but your Readme doc has a mapcidr.Ips reference:

```
// List all ips in the CIDR
	ips, _ := mapcidr.Ips("192.168.1.0/24")
	for _, ip := range ips {
		fmt.Println(ip)
	}
```
it should be just replaced by 

ips, _ := mapcidr.IPAddresses("192.168.1.0/24")

Ty!

**Comment by bauthard** [comment]
Thank you for pointing it out @dogasantos, the readme is aligned with the last stable release we created, we made a couple of changes after that and we planned to update them in the next release.

**Comment by Mzack9999** [comment]
Done in #7
