### ISSUE TITLE
Multi Format IP conversion support

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/mapcidr#80]
**Is your feature request related to a problem? Please describe.**

IP obfuscation can be used to bypass multiple waf/regex based protection which supposed to block specific IP format, multi format support could come handy to test those protections, hence adding IP conversation would be useful addition into mapcidr.

**Describe the solution you'd like**

```yaml
   -if, -ip-format  Covert IPs in given format (0,1,2,3,4,5,6,7,8)
```

```console
$ echo 127.0.0.1 | mapcidr -ip-format 0

127.1
0177.0.0.01
0x7f.0x0.0x0.0x1
2130706433
01111111000000000000000000000001
127.0x1
00:00:00:00:00:ffff:7f00:0001
%31%32%37%2E%30%2E%30%2E%31
```

More example inputs:

```
$ echo 192.168.1.0/24 | mapcidr -ip-format 1
$ cat cidrs.txt | mapcidr -ip-format 1
```

**Format to support and index to map with types:** 

Format | Index | Example
-- | -- | --
All | 0 |  `all below one`
0 Optimized dotted decimal | 1 | `127.1`
Octal | 2 | `0177.0.0.01`
Hexadecimal | 3 | `0x7f.0x0.0x0.0x1`
Dword | 4 | `2130706433`
Binary | 5 | `01111111000000000000000000000001`
Mixed | 6 | `127.0x1`
IPv6 | 7 | `00:00:00:00:00:ffff:7f00:0001`
URL encoded | 8 | `%31%32%37%2E%30%2E%30%2E%31`

Reference: https://www.hacksparrow.com/networking/many-faces-of-ip-address.html

**Comment by Mzack9999** [comment]
Additional mutations:
- [ ] Ip overflow (ref: https://twitter.com/ipinfoio/status/1539808210315526147)?
