### ISSUE TITLE
Make compatible with gologger >= 1.1.0

### ISSUE THREAD

**Issue by eclipseo** [projectdiscovery/mapcidr#9]
`github.com/projectdiscovery/gologger` was rewritten partially with breaking change wrt 1.0.1. It would be nice for `mapcidr` to be compatible with the latest version, so distro packagers don't have to use a compatibility package.

**Comment by ehsandeep** [comment]
@eclipseo this has been updated in the dev branch, soon we will merging changes into master and create a new release.
